version: '3.5'
services:
  frontend:
    build:
      context: frontend
      dockerfile: ./Dockerfile
      args:
      - NODE_ENV=development
    command: npm run start-watch
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 8080:8080
    volumes:
      - ./frontend/src:/code/src:ro
      - ./frontend/package.json:/code/package.json
      - ./frontend/package-lock.json:/code/package-lock.json
    networks:
      - public
    depends_on:
      - mariadb

  mariadb:
    build:
      context: db
      dockerfile: ./Dockerfile
    ports:
      - "3306:3306"
    restart: on-failure 
    environment: 
      - MYSQL_ROOT_PASSWORD="password"
      - MYSQL_PASSWORD="password"
      - MYSQL_USER="sql_user"
      - MYSQL_DATABASE="food"
    networks:
      - public
    volumes:
      - maria-data:/data/db

networks:
  public:
    driver: bridge

volumes:
  maria-data:
    driver: local